
version: '3.9'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: "184.72.86.165"
      DB_PORT: "3306"
      DB_USER: "dharaifood"
      DB_PASSWORD: "DharaiFood123!"
      DB_NAME: "dharaifood"

